export const OPEN = new Array();
export const HIGH = new Array();
export const LOW = new Array();
export const CLOSE = new Array();
export const VOLUME = new Array();
export const BASE_URL = "https://finance.yahoo.com/quote/{stock}/history?period1={start-date}&period2={end-date}&interval=1d&filter=history&frequency=1d&includeAdjustedClose=false";
export const MACD_URL = "https://www.investopedia.com/terms/m/macd.asp";
export const RSI_URL = "https://www.investopedia.com/terms/r/rsi.asp";
export const SIMPLE_AVERAGES_URL = "https://www.investopedia.com/terms/s/sma.asp";
export const EXPONENTIAL_AVERAGES_URL = "https://www.investopedia.com/terms/e/ema.asp";
export const BOLLINGER_BANDS_URL = "https://www.investopedia.com/terms/b/bollingerbands.asp";
